config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'

  #ingredients
  resources :ingredients, only: %i(new create index destroy edit update) do
  end

  # dishes
  resources :dishes do
    resources :ingredients_in_dishes, only: %i(new create destroy ) 
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :ingredients, through: :ingredients_in_dishes
  has_many :ingredients_in_dishes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :ingredients_in_dishes
  has_many :dishes, through: :ingredients_in_dishes
end

app/models/ingredients_in_dish.rb
class IngredientsInDish < ApplicationRecord
  belongs_to :ingredient
  belongs_to :dish
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  require 'byebug'
  before_action :set_dish, only: %i(destroy edit update show) 

  def new
    @dish = Dish.new
  end
  
  def create
    @dish = Dish.new(dish_params)
    if @dish.present?
      
      @dish.save
      redirect_to dishes_path
      flash[:notice] = "料理を登録しました"
    else
      redirect_to new_ingredient_path
      flash[:alert] = "登録に失敗しました"
    end
  end

  def index
    @dishes = Dish.all.order('created_at ASC')
  end  

  def show 
  end  

  def edit
  end
    
  def destroy
    @dish.destroy
    flash[:notice] = "データを破棄しました" 
    rescue
      flash[:alert] = "データの削除に失敗しました"
    ensure
      redirect_to dishes_path
  end  

  def update
    @dish.update(dish_params)
    flash[:notice] = "データを更新しました" 
    redirect_to dishes_path 
    rescue
      render 'edit'
      flash[:alert] = "データの更新に失敗しました"
  end


  private
    def dish_params
      params.require(:dish).permit(
        :title, :prep_time, :cook_time, :sit_time,
        :yield
      )
    end

    def set_dish
      @dish = Dish.find_by(id: params[:id])
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  require 'byebug'
  before_action :set_ingredient, only: %i(destroy edit update)

  def new
    @ingredient = Ingredient.new
  end
  
  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.present?
      # byebug
      @ingredient.save
      redirect_to ingredients_path
      flash[:notice] = "材料を登録しました"
    else
      redirect_to new_ingredient_path
      flash[:alert] = "登録に失敗しました"
    end
  end

  def destroy
    @ingredient.destroy
    flash[:notice] = "データを破棄しました" 
    rescue
      flash[:alert] = "データの削除に失敗しました"
    ensure
      redirect_to ingredients_path
  end

  def index
    @ingredients = Ingredient.all.order('created_at ASC')
  end  

  def edit
  end  

  def update
    @ingredient.update(ingredient_params)
    flash[:notice] = "データを更新しました" 
    redirect_to ingredients_path 
    rescue
      render 'edit'
      flash[:alert] = "データの更新に失敗しました"
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(
          :title, :meat, :dairy_egg, :seafood, :other_animal, 
          :allergen, :protein, :fat, :carbs, :cost
      )
    end

    def set_ingredient
      @ingredient = Ingredient.find_by(id: params[:id])
    end

end

app/controllers/ingredients_in_dishes_controller.rb
class IngredientsInDishesController < ApplicationController

  before_action :set_ingredients_in_dish, only: %i(destroy edit update show) 
  require 'byebug'
  def create
    dish = Dish.find_by(id: params[:dish_id])
    ingredients_in_dish = dish.ingredients_in_dishes.build(ingredients_in_dish_params)
    if ingredients_in_dish.save
      redirect_to dishes_path
      flash[:notice] = "料理に材料を登録しました"
    else
      redirect_to new_dish_ingredients_in_dish_path
      flash[:alert] = "登録に失敗しました"
    end  
  end

  def destroy
    @ingredients_in_dish.destroy
    flash[:notice] = "データを破棄しました" 
    rescue
      flash[:alert] = "データの削除に失敗しました"
    ensure
      redirect_to dishes_path
  end  
  
private
  def ingredients_in_dish_params
    params.permit(
      :dish_id, :ingredient_id, :unit, :gram, 
    )
  end

  def set_ingredients_in_dish
    @ingredients_in_dish = IngredientsInDish.find_by(id: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/ingredients_in_dishes_helper.rb
module IngredientsInDishesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dishes/edit.html.erb
<div class="main">
  <div class="card mt-2 w-75 mx-auto">
    <div class="form-group text-center mt-4">
      <h2 class="text-secondary">料理編集</h2>
    </div>
    <%# TODO: 名前が一緒の時、空の時にエラー吐くようにする idea：redirectをshowに送る→なければエラー %>
    <div class="form-wrap m-2">
      <%= form_with model: @dish do |f| %>
        <div class="form-group text-center w-50 mx-auto mt-2">
          <%= f.text_field :title, required: true, placeholder: "タイトル" %>
        </div>
        <div class="form-group text-center mt-4">
          <h4 class="text-secondary">トータルタイム</h4>
        </div>
        <div class="form-group d-flex justify-content-around mt-2 mx-auto">
          <div class="d-inline-block">
            <%= f.number_field :prep_time, step: "1", required: true, placeholder: "下準備時間" %>
            <%= label_tag(:prep_time, "min", class:"mr-2") %> 
          </div>
          <div class="d-inline-block">
            <%= f.number_field :cook_time,  step: "1", required: true, placeholder: "調理時間" %>
            <%= label_tag(:cook_time, "min") %>
          </div>
          <div class="d-inline-block">
            <%= f.number_field :sit_time, step: "1", required: true, placeholder: "寝かし、漬け込み 時間" %>
            <%= label_tag(:sit_time, "min") %>
          </div>
        </div>
        <div class="form-group text-center mt-4">
          <h4 class="text-secondary">出来上がり量</h4>
        </div>
        <div class="form-group text-center w-75 mt-2 mx-auto">
          <%= f.number_field :yield, step: "1", required: true %>
          <%= label_tag(:yeild, "人前") %>
        </div>
        <div class="actions mt-4">
          <%= f.submit "更新", class: "btn btn-primary d-block ms-auto" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dishes/index.html.erb
<div class="main">
  <div class="form-group text-center mt-4">
    <h2 class="text-secondary">料理一覧</h2>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">料理タイトル</th>
        <th scope="col">下処理時間</th>
        <th scope="col">調理時間</th>
        <th scope="col">発酵/漬け込み 時間</th>
        <th scope="col">出来上がり量</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @dishes.each do |d| %>
        <tr>
          <th scope="row">
            <%= link_to dish_path(d) do %>
              <%= d.title %>
            <% end %>
          </th>
          <td><%= d.prep_time %>分</td>
          <td><%= d.cook_time %>分</td>
          <td><%= d.sit_time %>分</td>
          <td><%= d.yield %>人前</td>
          <td class="d-flex justify-content-between">
            <%= link_to edit_dish_path(d) do %>
              <i class="far fa-edit mr-2"></i>
            <% end %>
            <%= link_to dish_path(d), method: :delete do %>
              <i class="fa fa-trash-alt mr-2"></i>
            <% end %>
          </td>
          <%# TODO: フードタイプの表示もする idea：HelperメソッドにtrueならIconを出すようにメソッド  %>
        </tr>
      <% end %>  
    </tbody>
  </table>
  <div class="mt-4">
    <div class="w-75">
      <%= link_to new_dish_path do %>
        <i class="far fa-2x fa-plus-square ms-auto"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/dishes/new.html.erb
<div class="main">
  <div class="card mt-2 w-75 mx-auto">
    <div class="form-group text-center mt-4">
      <h2 class="text-secondary">料理登録</h2>
    </div>
    <%# TODO: 名前が一緒の時、空の時にエラー吐くようにする idea：redirectをshowに送る→なければエラー %>
    <div class="form-wrap m-2">
      <%= form_with model: @dish do |f| %>
        <div class="form-group text-center w-50 mx-auto mt-2">
          <%= f.text_field :title, required: true, placeholder: "タイトル" %>
        </div>
        <div class="form-group text-center mt-4">
          <h4 class="text-secondary">トータルタイム</h4>
        </div>
        <div class="form-group d-flex justify-content-around mt-2 mx-auto">
          <div class="d-inline-block">
            <%= f.number_field :prep_time, step: "1", required: true, placeholder: "下準備時間" %>
            <%= label_tag(:prep_time, "min", class:"mr-2") %> 
          </div>
          <div class="d-inline-block">
            <%= f.number_field :cook_time,  step: "1", required: true, placeholder: "調理時間" %>
            <%= label_tag(:cook_time, "min") %>
          </div>
          <div class="d-inline-block">
            <%= f.number_field :sit_time, step: "1", required: true, placeholder: "寝かし、漬け込み 時間" %>
            <%= label_tag(:sit_time, "min") %>
          </div>
        </div>
        <div class="form-group text-center mt-4">
          <h4 class="text-secondary">出来上がり量</h4>
        </div>
        <div class="form-group text-center w-75 mt-2 mx-auto">
          <%= f.number_field :yield, step: "1", required: true %>
          <%= label_tag(:yeild, "人前") %>
        </div>
        <div class="actions mt-4">
          <%= f.submit "登録", class: "btn btn-primary d-block ms-auto" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dishes/show.html.erb
<div class="main">
  <div class="text-center mt-4">
    <h2 class="text-secondary"><%= @dish.title %></h2>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">材料</th>
        <th scope="col">分量</th>
        <th scope="col">分量(g)</th>
        <th scope="col">action</th>
      </tr>
    </thead>
    <tbody>
      <% @dish.ingredients_in_dishes.each do |d| %>
        <tr>
          <th scope="row"><%= d.ingredient.title %></th>
          <td><%= d.unit %></td>
          <td><%= d.gram %>g</td>
          <td class="d-flex justify-content-between">
            <%# ↓↓↓ なぜかparamsがぐちゃぐちゃに渡されるので指定してる %>
            <%= link_to dish_ingredients_in_dish_path(id: d.id, dish_id: d.dish_id), method: :delete do %> 
              <i class="fa fa-trash-alt mr-2"></i>
            <% end %>
          </td>
          <%# TODO: フードタイプの表示もする idea：HelperメソッドにtrueならIconを出すようにメソッド  %>
        </tr>
      <% end %>  
    </tbody>
  </table>
  <div class="mt-4">
    <div class="w-75">
      <%= link_to new_dish_ingredients_in_dish_path(@dish) do %>
        <i class="far fa-2x fa-plus-square ms-auto"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/edit.html.erb
<div class="main">
  <div class="card mt-2 w-75 mx-auto">
    <div class="form-group text-center mt-4">
      <h2 class="text-secondary">材料登録</h2>
    </div>
    <%# TODO: 名前が一緒の時、空の時にエラー吐くようにする idea：redirectをshowに送る→なければエラー %>
    <div class="form-wrap m-2">
      <%= form_with model: @ingredient do |f| %>
        <div class="form-group text-center w-50 mx-auto mt-2">
          <%= f.text_field :title, required: true, placeholder: "材料名" %>
        </div>
        <div class="form-group text-center mt-4">
          <h4 class="text-secondary">pfc値</h4>
        </div>
        <div class="form-group d-flex justify-content-around mt-2 mx-auto">
          <div class="d-inline-block">
            <%= f.number_field :protein, step: "0.1", required: true, placeholder: "タンパク質" %>
            <%= label_tag(:protein, "(g)/100g", class:"mr-2") %> 
          </div>
          <div class="d-inline-block">
            <%= f.number_field :fat,  step: "0.1", required: true, placeholder: "脂質" %>
            <%= label_tag(:fat, "(g)/100g") %>
          </div>
          <div class="d-inline-block">
            <%= f.number_field :carbs, step: "0.1", required: true, placeholder: "糖質" %>
            <%= label_tag(:carbs, "(g)/100g") %>
          </div>
        </div>
        <div class="form-group text-center mt-4">
          <h4 class="text-secondary">コスト</h4>
        </div>
        <div class="form-group text-center w-75 mt-2 mx-auto">
          <%= f.number_field :cost, step: "1", required: true, placeholder: "価格" %>
          <%= label_tag(:cost, "(¥)/100g") %>
        </div>
        <div class="form-group text-center w-75 mt-4 mx-auto">
          <%= f.check_box :meat %>
          <%= label_tag(:meat, "肉を含む") %>
          <%= f.check_box :dairy_egg %>
          <%= label_tag( :dairy_egg, "卵・乳製品を含む") %>
          <%= f.check_box :seafood %>
          <%= label_tag(:seafood, "魚介類を含む") %>
          <%= f.check_box :other_animal %>
          <%= label_tag(:other_animal, "その他動物性を含む") %>
          <%= f.check_box :allergen %>
          <%= label_tag(:allergen, "アレルゲンを含む") %>
        </div>
        <div class="actions mt-4">
          <%= f.submit "登録", class: "btn btn-primary d-block ms-auto" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class="main">
  <div class="form-group text-center mt-4">
    <h2 class="text-secondary">材料一覧</h2>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">＃</th>
        <th scope="col">材料名</th>
        <th scope="col">p</th>
        <th scope="col">f</th>
        <th scope="col">c</th>
        <th scope="col">価格</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @ingredients.each do |i| %>
        <tr>
          <th scope="row"><%= i.id %></th>
          <td><%= i.title %></td>
          <td><%= i.protein %>g /100g</td>
          <td><%= i.fat %>g /100g</td>
          <td><%= i.carbs %>g /100g</td>
          <td>¥<%= i.cost %> /100g</td>
          <td class="d-flex justify-content-between">
            <%= link_to edit_ingredient_path(i) do %>
              <i class="far fa-edit mr-2"></i>
            <% end %>
            <%= link_to ingredient_path(i), method: :delete do %>
              <i class="fa fa-trash-alt mr-2"></i>
            <% end %>
          </td>
          <%# TODO: フードタイプの表示もする idea：HelperメソッドにtrueならIconを出すようにメソッド  %>
        </tr>
      <% end %>  
    </tbody>
  </table>
  <div class="mt-4">
    <div class="w-75">
      <%= link_to new_ingredient_path do %>
        <i class="far fa-2x fa-plus-square ms-auto"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="main">
  <div class="card mt-2 w-75 mx-auto">
    <div class="form-group text-center mt-4">
      <h2 class="text-secondary">材料登録</h2>
    </div>
    <%# TODO: 名前が一緒の時、空の時にエラー吐くようにする idea：redirectをshowに送る→なければエラー %>
    <div class="form-wrap m-2">
      <%= form_with model: @ingredient do |f| %>
        <div class="form-group text-center w-50 mx-auto mt-2">
          <%= f.text_field :title, required: true, placeholder: "材料名" %>
        </div>
        <div class="form-group text-center mt-4">
          <h4 class="text-secondary">pfc値</h4>
        </div>
        <div class="form-group d-flex justify-content-around mt-2 mx-auto">
          <div class="d-inline-block">
            <%= f.number_field :protein, step: "0.1", required: true, placeholder: "タンパク質" %>
            <%= label_tag(:protein, "(g)/100g", class:"mr-2") %> 
          </div>
          <div class="d-inline-block">
            <%= f.number_field :fat,  step: "0.1", required: true, placeholder: "脂質" %>
            <%= label_tag(:fat, "(g)/100g") %>
          </div>
          <div class="d-inline-block">
            <%= f.number_field :carbs, step: "0.1", required: true, placeholder: "糖質" %>
            <%= label_tag(:carbs, "(g)/100g") %>
          </div>
        </div>
        <div class="form-group text-center mt-4">
          <h4 class="text-secondary">コスト</h4>
        </div>
        <div class="form-group text-center w-75 mt-2 mx-auto">
          <%= f.number_field :cost, step: "1", required: true, placeholder: "価格" %>
          <%= label_tag(:cost, "(¥)/100g") %>
        </div>
        <div class="form-group text-center w-75 mt-4 mx-auto">
          <%= f.check_box :meat %>
          <%= label_tag(:meat, "肉を含む") %>
          <%= f.check_box :dairy_egg %>
          <%= label_tag( :dairy_egg, "卵・乳製品を含む") %>
          <%= f.check_box :seafood %>
          <%= label_tag(:seafood, "魚介類を含む") %>
          <%= f.check_box :other_animal %>
          <%= label_tag(:other_animal, "その他動物性を含む") %>
          <%= f.check_box :allergen %>
          <%= label_tag(:allergen, "アレルゲンを含む") %>
        </div>
        <div class="actions mt-4">
          <%= f.submit "登録", class: "btn btn-primary d-block ms-auto" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients_in_dishes/new.html.erb
<div class="main">
  <div class="card mt-2 w-75 mx-auto">
    <div class="form-group text-center mt-4">
      <h2 class="text-secondary"></h2>
    </div>
    <%# TODO: 名前が一緒の時、空の時にエラー吐くようにする idea：redirectをshowに送る→なければエラー %>
    <div class="form-wrap m-2">
      <%= form_with model: @ingredients_in_dish, url: dish_ingredients_in_dishes_path, local: true do |f| %>
        <div class="form-group text-center w-75 mx-auto mt-2">
          <%= f.collection_select :ingredient_id, Ingredient.all, :id, :title, :prompt =>"材料を選択" %>
        </div>
        <div class="form-group text-center w-75 mx-auto mt-2">
          <%= f.text_field :unit, required: true, placeholder: "分量 ex) 大さじ１、1/2個" %>
        </div>
        <div class="form-group d-flex justify-content-around mt-2 mx-auto">
          <div class="d-inline-block">
            <%= f.number_field :gram, step: "0.1", required: true, placeholder: "分量（g）" %>
            <%= label_tag(:gram, "g", class:"mr-2") %> 
          </div>
        </div>
        <div class="actions mt-4">
          <%= f.submit "登録", class: "btn btn-primary d-block ms-auto" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocinaap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'partial/navbar'%>
    
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>  
    </div>  

    <%= render 'partial/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<p>仮トップやで</P>
<i class="far fa-address-book"></i>
<i class="fab fa-github"></i>

<% if user_signed_in? %> 
  <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
<% end %>

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Copyright © Cocinaap
      </p>
    </div>
  </div>
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>